version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: tasksouk
      POSTGRES_PASSWORD: tasksouk
      POSTGRES_DB: TaskServiceDB
    ports:
      - "5432:5432"
    volumes:
      - mydbdata:/var/lib/postgresql/data

volumes:
  mydbdata:
